### ISSUE TITLE
Evaluation article RZine

### ISSUE THREAD

**Issue by beauguitte** [carmand03/place-rzine#1]

**Comment by carmand03** [comment]
Merci à Laurent Beauguitte pour sa lecture attentive et ses remarques constructives. 

Je me suis efforcée de les intégrer au mieux dans la version révisée. Ci-dessous je justifie celles auxquelles je n’ai pas pu répondre : 

- Comparer projection classique / projection basée sur places. C’est une très bonne suggestion, mais j’ai préféré la garder pour un autre tutoriel, et me concentrer ici sur l’introduction du package places et le déroulé d’une méthode adaptée (en conséquence, j’ai revu les prétentions de la conclusion à la baisse). 

- De même pour la détection de communautés, je préfère ici me concentrer sur Louvain. Comparer différents algorithmes dépasse l’ambition de ce tutoriel. En réalité, j’ai fait ce travail de comparaison dans la phase exploratoire, mais j’ai trouvé que les partitions obtenues avec d’autres algorithmes étaient moins intéressantes à interpréter. J’ai néanmoins souligné dans une note la nécessité de comparer différents algorithmes avant de choisir. J’ai aussi indiqué le lien vers un tuto plus complet expliquant comment faire. 

- La fonction “plot.communities” ne semble plus exister ?

- Je ne suis pas sûre de bien comprendre la question concernant la modularité: “L523: Quelle est la source pour la limite inférieure de la modularité (-0.5) ?”

J’attends les retours du second évaluateur pour soumettre la version révisée (y a-t-il une double évaluation ?). 

Merci, Cécile A

**Comment by beauguitte** [comment]
Bonjour,
oui, il y a une double évaluation donc autant attendre la suite.
Pour les deux derniers points:
- effectivement, je me suis trompé sur ce point. Mais il me semble que les deux lignes affectant une couleur aux communautés (538-539) ne sont pas nécessaires (idem donc pour la ligne 536). Si l'on fournit à la fonction plot d'igraph un réseau et une partition, il affectera automatiquement une couleur différente aux différentes communautés ; 
- concernant la modularité, la limite supérieure est à 1. La modularité peut être négative. Mais je n'ai pas mémoire de texte indiquant une limite inférieure égale à -0.5 (note 7 de la proposition). Si l'autrice a une référence pour ce point, je suis preneur !
Un grand merci en tout cas pour cette proposition !
